title: FBIMS
description: Documentation for the Food Bank Inventory Management System
theme: just-the-docs

url: https://codevalve.github.io/foodbank
baseurl: ""

aux_links:
  GitHub Repository: https://github.com/codevalve/foodbank

# Enable search
search_enabled: true

# Enable anchor links
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Food Bank Inventory Management System. Distributed under an <a href=\"https://github.com/codevalve/foodbank/tree/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
