source 'https://rubygems.org'

gem "github-pages", group: :jekyll_plugins
gem "just-the-docs", "~> 0.7.0"

group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-seo-tag"
  gem "jekyll-feed"
end
